version: '3'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    extra_hosts:
      - "buyingcatalogue-development-helm-dev.buyingcatalogue.digital.nhs.uk:51.11.46.27"
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "buyingcatalogue-development-helm-dev.buyingcatalogue.digital.nhs.uk:51.11.46.27"
  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "buyingcatalogue-development-helm-dev.buyingcatalogue.digital.nhs.uk:51.11.46.27"